<?php

namespace MarsupilamiBundle\Repository;

use Doctrine\ORM\Query;

/**
 * MarsupilamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarsupilamiRepository extends \Doctrine\ORM\EntityRepository {

    public function friends($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u,a')
                        ->from('MarsupilamiBundle:Marsupilami', 'u')
                        ->leftJoin('u.friends', 'a')
                        ->where('u.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }

    public function users() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u')
                        ->from('MarsupilamiBundle:Marsupilami', 'u')
                        ->getQuery()
                        ->getResult(Query::HYDRATE_ARRAY);
    }

}
